/**
 * Adyen HPP
 * Hosted Payment Pages
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/IssuersType', 'model/PaymentMethodsType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./IssuersType'), require('./PaymentMethodsType'));
  } else {
    // Browser globals (root is window)
    if (!root.AdyenHppJs) {
      root.AdyenHppJs = {};
    }
    root.AdyenHppJs.DirectoryResponse = factory(root.AdyenHppJs.ApiClient, root.AdyenHppJs.IssuersType, root.AdyenHppJs.PaymentMethodsType);
  }
}(this, function(ApiClient, IssuersType, PaymentMethodsType) {
  'use strict';




  /**
   * The DirectoryResponse model module.
   * @module model/DirectoryResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>DirectoryResponse</code>.
   * @alias module:model/DirectoryResponse
   * @class
   * @param paymentMethods {module:model/PaymentMethodsType} 
   */
  var exports = function(paymentMethods) {
    var _this = this;

    _this['paymentMethods'] = paymentMethods;

  };

  /**
   * Constructs a <code>DirectoryResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DirectoryResponse} obj Optional instance to populate.
   * @return {module:model/DirectoryResponse} The populated <code>DirectoryResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('paymentMethods')) {
        obj['paymentMethods'] = PaymentMethodsType.constructFromObject(data['paymentMethods']);
      }
      if (data.hasOwnProperty('issuers')) {
        obj['issuers'] = IssuersType.constructFromObject(data['issuers']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/PaymentMethodsType} paymentMethods
   */
  exports.prototype['paymentMethods'] = undefined;
  /**
   * @member {module:model/IssuersType} issuers
   */
  exports.prototype['issuers'] = undefined;


  /**
   * @return {module:model/PaymentMethodsType}
   */
  exports.prototype.getPaymentMethods = function() {
    return this['paymentMethods'];
  }

  /**
   * @param {module:model/PaymentMethodsType} paymentMethods
   */
  exports.prototype.setPaymentMethods = function(paymentMethods) {
    this['paymentMethods'] = paymentMethods;
  }


  /**
   * @return {module:model/IssuersType}
   */
  exports.prototype.getIssuers = function() {
    return this['issuers'];
  }

  /**
   * @param {module:model/IssuersType} issuers
   */
  exports.prototype.setIssuers = function(issuers) {
    this['issuers'] = issuers;
  }



  return exports;
}));


