/**
 * Adyen HPP
 * Hosted Payment Pages
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DirectoryRequest', 'model/Error'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/DirectoryRequest'), require('../model/Error'));
  } else {
    // Browser globals (root is window)
    if (!root.AdyenHppJs) {
      root.AdyenHppJs = {};
    }
    root.AdyenHppJs.DirectoryApi = factory(root.AdyenHppJs.ApiClient, root.AdyenHppJs.DirectoryRequest, root.AdyenHppJs.Error);
  }
}(this, function(ApiClient, DirectoryRequest, Error) {
  'use strict';

  /**
   * Directory service.
   * @module api/DirectoryApi
   * @version 1.0.0
   */

  /**
   * Constructs a new DirectoryApi. 
   * @alias module:api/DirectoryApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Directory lookup
     * Optionally, you may choose to host the payment selection on your website and skip the HPP part (directory lookup). Directory lookup enables you to directly show the entry fields for the selected payment methods to shoppers. It sends information such as the shopper location, shopping basket value and currency to the Adyen Payment Platform, which dynamically provides the list of the most relevant payment methods for this shopper to the merchant. By using this payment data, you can dynamically generate a customized payment page allowing the shopper to complete their purchase using a targeted selection of payment methods.  By selecting a payment method, the shopper is redirected to the local payment method check out of his choice, for example the shopper’s own bank iDEAL page, the shopper&#39;s own bank Suomen Verkumaksut page, PayPal page, etc. Following any payment request, Adyen sends back a notification providing the status of the payment and updates the status as soon as it changes. This means that our customers receive information about the status of the request in all cases.
     * @param {module:model/DirectoryRequest} directoryRequest The Directory Request
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.directory = function(directoryRequest) {
      var postBody = directoryRequest;

      // verify the required parameter 'directoryRequest' is set
      if (directoryRequest == undefined || directoryRequest == null) {
        throw new Error("Missing the required parameter 'directoryRequest' when calling directory");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/directory.shtml', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }
  };

  return exports;
}));
