/**
 * Adyen HPP
 * Hosted Payment Pages
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Error', 'model/SkipDetailsRequest'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Error'), require('../model/SkipDetailsRequest'));
  } else {
    // Browser globals (root is window)
    if (!root.AdyenHppJs) {
      root.AdyenHppJs = {};
    }
    root.AdyenHppJs.SkipDetailsApi = factory(root.AdyenHppJs.ApiClient, root.AdyenHppJs.Error, root.AdyenHppJs.SkipDetailsRequest);
  }
}(this, function(ApiClient, Error, SkipDetailsRequest) {
  'use strict';

  /**
   * SkipDetails service.
   * @module api/SkipDetailsApi
   * @version 1.0.0
   */

  /**
   * Constructs a new SkipDetailsApi. 
   * @alias module:api/SkipDetailsApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Skip HPP
     * If you want, you can skip displaying the payment method selection page with the list of available payment methods returned by the directory lookup. You can route your shopper directly to the payment or order detail entry page.
     * @param {module:model/SkipDetailsRequest} skipDetailsRequest The SkipDetails Request
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.skipDetails = function(skipDetailsRequest) {
      var postBody = skipDetailsRequest;

      // verify the required parameter 'skipDetailsRequest' is set
      if (skipDetailsRequest == undefined || skipDetailsRequest == null) {
        throw new Error("Missing the required parameter 'skipDetailsRequest' when calling skipDetails");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/skipDetails.shtml', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }
  };

  return exports;
}));
