/**
 * Adyen HPP
 * Hosted Payment Pages
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AdyenHppJs);
  }
}(this, function(expect, AdyenHppJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AdyenHppJs.DirectoryRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DirectoryRequest', function() {
    it('should create an instance of DirectoryRequest', function() {
      // uncomment below and update the code to test DirectoryRequest
      //var instane = new AdyenHppJs.DirectoryRequest();
      //expect(instance).to.be.a(AdyenHppJs.DirectoryRequest);
    });

    it('should have the property currencyCode (base name: "currencyCode")', function() {
      // uncomment below and update the code to test the property currencyCode
      //var instane = new AdyenHppJs.DirectoryRequest();
      //expect(instance).to.be();
    });

    it('should have the property merchantAccount (base name: "merchantAccount")', function() {
      // uncomment below and update the code to test the property merchantAccount
      //var instane = new AdyenHppJs.DirectoryRequest();
      //expect(instance).to.be();
    });

    it('should have the property paymentAmount (base name: "paymentAmount")', function() {
      // uncomment below and update the code to test the property paymentAmount
      //var instane = new AdyenHppJs.DirectoryRequest();
      //expect(instance).to.be();
    });

    it('should have the property skinCode (base name: "skinCode")', function() {
      // uncomment below and update the code to test the property skinCode
      //var instane = new AdyenHppJs.DirectoryRequest();
      //expect(instance).to.be();
    });

    it('should have the property merchantReference (base name: "merchantReference")', function() {
      // uncomment below and update the code to test the property merchantReference
      //var instane = new AdyenHppJs.DirectoryRequest();
      //expect(instance).to.be();
    });

    it('should have the property sessionValidity (base name: "sessionValidity")', function() {
      // uncomment below and update the code to test the property sessionValidity
      //var instane = new AdyenHppJs.DirectoryRequest();
      //expect(instance).to.be();
    });

    it('should have the property merchantSig (base name: "merchantSig")', function() {
      // uncomment below and update the code to test the property merchantSig
      //var instane = new AdyenHppJs.DirectoryRequest();
      //expect(instance).to.be();
    });

    it('should have the property countryCode (base name: "countryCode")', function() {
      // uncomment below and update the code to test the property countryCode
      //var instane = new AdyenHppJs.DirectoryRequest();
      //expect(instance).to.be();
    });

  });

}));
