/**
 * Adyen HPP
 * Hosted Payment Pages
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AdyenHppJs);
  }
}(this, function(expect, AdyenHppJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AdyenHppJs.PaymentRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PaymentRequest', function() {
    it('should create an instance of PaymentRequest', function() {
      // uncomment below and update the code to test PaymentRequest
      //var instane = new AdyenHppJs.PaymentRequest();
      //expect(instance).to.be.a(AdyenHppJs.PaymentRequest);
    });

    it('should have the property merchantReference (base name: "merchantReference")', function() {
      // uncomment below and update the code to test the property merchantReference
      //var instane = new AdyenHppJs.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property paymentAmount (base name: "paymentAmount")', function() {
      // uncomment below and update the code to test the property paymentAmount
      //var instane = new AdyenHppJs.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property currencyCode (base name: "currencyCode")', function() {
      // uncomment below and update the code to test the property currencyCode
      //var instane = new AdyenHppJs.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property shipBeforeDate (base name: "shipBeforeDate")', function() {
      // uncomment below and update the code to test the property shipBeforeDate
      //var instane = new AdyenHppJs.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property skinCode (base name: "skinCode")', function() {
      // uncomment below and update the code to test the property skinCode
      //var instane = new AdyenHppJs.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property merchantAccount (base name: "merchantAccount")', function() {
      // uncomment below and update the code to test the property merchantAccount
      //var instane = new AdyenHppJs.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property shopperLocale (base name: "shopperLocale")', function() {
      // uncomment below and update the code to test the property shopperLocale
      //var instane = new AdyenHppJs.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property orderData (base name: "orderData")', function() {
      // uncomment below and update the code to test the property orderData
      //var instane = new AdyenHppJs.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property sessionValidity (base name: "sessionValidity")', function() {
      // uncomment below and update the code to test the property sessionValidity
      //var instane = new AdyenHppJs.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property merchantReturnData (base name: "merchantReturnData")', function() {
      // uncomment below and update the code to test the property merchantReturnData
      //var instane = new AdyenHppJs.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property merchantSig (base name: "merchantSig")', function() {
      // uncomment below and update the code to test the property merchantSig
      //var instane = new AdyenHppJs.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property countryCode (base name: "countryCode")', function() {
      // uncomment below and update the code to test the property countryCode
      //var instane = new AdyenHppJs.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property shopperEmail (base name: "shopperEmail")', function() {
      // uncomment below and update the code to test the property shopperEmail
      //var instane = new AdyenHppJs.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property shopperReference (base name: "shopperReference")', function() {
      // uncomment below and update the code to test the property shopperReference
      //var instane = new AdyenHppJs.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property allowedMethods (base name: "allowedMethods")', function() {
      // uncomment below and update the code to test the property allowedMethods
      //var instane = new AdyenHppJs.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property blockedMethods (base name: "blockedMethods")', function() {
      // uncomment below and update the code to test the property blockedMethods
      //var instane = new AdyenHppJs.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property offset (base name: "offset")', function() {
      // uncomment below and update the code to test the property offset
      //var instane = new AdyenHppJs.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property brandCode (base name: "brandCode")', function() {
      // uncomment below and update the code to test the property brandCode
      //var instane = new AdyenHppJs.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property issuerId (base name: "issuerId")', function() {
      // uncomment below and update the code to test the property issuerId
      //var instane = new AdyenHppJs.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property shopperStatement (base name: "shopperStatement")', function() {
      // uncomment below and update the code to test the property shopperStatement
      //var instane = new AdyenHppJs.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property offerEmail (base name: "offerEmail")', function() {
      // uncomment below and update the code to test the property offerEmail
      //var instane = new AdyenHppJs.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property telephoneNumber (base name: "telephoneNumber")', function() {
      // uncomment below and update the code to test the property telephoneNumber
      //var instane = new AdyenHppJs.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property resURL (base name: "resURL")', function() {
      // uncomment below and update the code to test the property resURL
      //var instane = new AdyenHppJs.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property recurringContract (base name: "recurringContract")', function() {
      // uncomment below and update the code to test the property recurringContract
      //var instane = new AdyenHppJs.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property metadata (base name: "metadata")', function() {
      // uncomment below and update the code to test the property metadata
      //var instane = new AdyenHppJs.PaymentRequest();
      //expect(instance).to.be();
    });

  });

}));
