/**
 * Adyen HPP
 * Hosted Payment Pages
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AuthResultType', 'model/DirectoryRequest', 'model/DirectoryResponse', 'model/Error', 'model/ErrorType', 'model/IssuersType', 'model/PaymentMethodsType', 'model/PaymentRequest', 'model/PaymentResponse', 'model/RecurringContractType', 'model/SkipDetailsRequest', 'model/SkipDetailsResponse', 'api/DirectoryApi', 'api/PayApi', 'api/SelectApi', 'api/SkipDetailsApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/AuthResultType'), require('./model/DirectoryRequest'), require('./model/DirectoryResponse'), require('./model/Error'), require('./model/ErrorType'), require('./model/IssuersType'), require('./model/PaymentMethodsType'), require('./model/PaymentRequest'), require('./model/PaymentResponse'), require('./model/RecurringContractType'), require('./model/SkipDetailsRequest'), require('./model/SkipDetailsResponse'), require('./api/DirectoryApi'), require('./api/PayApi'), require('./api/SelectApi'), require('./api/SkipDetailsApi'));
  }
}(function(ApiClient, AuthResultType, DirectoryRequest, DirectoryResponse, Error, ErrorType, IssuersType, PaymentMethodsType, PaymentRequest, PaymentResponse, RecurringContractType, SkipDetailsRequest, SkipDetailsResponse, DirectoryApi, PayApi, SelectApi, SkipDetailsApi) {
  'use strict';

  /**
   * Hosted_Payment_Pages.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var AdyenHppJs = require('index'); // See note below*.
   * var xxxSvc = new AdyenHppJs.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new AdyenHppJs.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new AdyenHppJs.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new AdyenHppJs.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The AuthResultType model constructor.
     * @property {module:model/AuthResultType}
     */
    AuthResultType: AuthResultType,
    /**
     * The DirectoryRequest model constructor.
     * @property {module:model/DirectoryRequest}
     */
    DirectoryRequest: DirectoryRequest,
    /**
     * The DirectoryResponse model constructor.
     * @property {module:model/DirectoryResponse}
     */
    DirectoryResponse: DirectoryResponse,
    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error: Error,
    /**
     * The ErrorType model constructor.
     * @property {module:model/ErrorType}
     */
    ErrorType: ErrorType,
    /**
     * The IssuersType model constructor.
     * @property {module:model/IssuersType}
     */
    IssuersType: IssuersType,
    /**
     * The PaymentMethodsType model constructor.
     * @property {module:model/PaymentMethodsType}
     */
    PaymentMethodsType: PaymentMethodsType,
    /**
     * The PaymentRequest model constructor.
     * @property {module:model/PaymentRequest}
     */
    PaymentRequest: PaymentRequest,
    /**
     * The PaymentResponse model constructor.
     * @property {module:model/PaymentResponse}
     */
    PaymentResponse: PaymentResponse,
    /**
     * The RecurringContractType model constructor.
     * @property {module:model/RecurringContractType}
     */
    RecurringContractType: RecurringContractType,
    /**
     * The SkipDetailsRequest model constructor.
     * @property {module:model/SkipDetailsRequest}
     */
    SkipDetailsRequest: SkipDetailsRequest,
    /**
     * The SkipDetailsResponse model constructor.
     * @property {module:model/SkipDetailsResponse}
     */
    SkipDetailsResponse: SkipDetailsResponse,
    /**
     * The DirectoryApi service constructor.
     * @property {module:api/DirectoryApi}
     */
    DirectoryApi: DirectoryApi,
    /**
     * The PayApi service constructor.
     * @property {module:api/PayApi}
     */
    PayApi: PayApi,
    /**
     * The SelectApi service constructor.
     * @property {module:api/SelectApi}
     */
    SelectApi: SelectApi,
    /**
     * The SkipDetailsApi service constructor.
     * @property {module:api/SkipDetailsApi}
     */
    SkipDetailsApi: SkipDetailsApi
  };

  return exports;
}));
